/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import CapaLogica.BLAuto;
import CapaLogica.BLClientes;
import CapaLogica.BLEmpleados;
import CapaLogica.BLReparaciones;
import CapaLogica.BLServicios;
import Capa_Entidades.EntidadAutomovil;
import Capa_Entidades.EntidadCliente;
import Capa_Entidades.EntidadEmpleado;
import Capa_Entidades.EntidadReparaciones;
import Capa_Entidades.Entidad_Servicio;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/**
 *
 * @author Fran
 */
public class Frm_Agenda_Reparacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Agenda_Reparacion
     */
    public Frm_Agenda_Reparacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDServicio = new javax.swing.JLabel();
        txtID_Servicio = new javax.swing.JTextField();
        btnbuscarservicio = new javax.swing.JButton();
        lblIDEmpleado = new javax.swing.JLabel();
        txtID_Empleado = new javax.swing.JTextField();
        btnbuscarempleado = new javax.swing.JButton();
        lblID_Auto = new javax.swing.JLabel();
        txtID_Auto = new javax.swing.JTextField();
        btnbuscarauto = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Txttipovehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FechaFin = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnAgendar = new javax.swing.JButton();
        dtchFin = new com.toedter.calendar.JDateChooser();
        dtchInicio = new com.toedter.calendar.JDateChooser();
        btnSalir = new javax.swing.JButton();

        lblIDServicio.setText("ID_Servicio");

        txtID_Servicio.setEditable(false);

        btnbuscarservicio.setText("Buscar Servicio");
        btnbuscarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarservicioActionPerformed(evt);
            }
        });

        lblIDEmpleado.setText("ID_Empleado");

        txtID_Empleado.setEditable(false);

        btnbuscarempleado.setText("Buscar Empleado");
        btnbuscarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarempleadoActionPerformed(evt);
            }
        });

        lblID_Auto.setText("ID_Auto");

        txtID_Auto.setEditable(false);

        btnbuscarauto.setText("Buscar Auto");
        btnbuscarauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarautoActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        txtID.setEditable(false);

        jLabel1.setText("Tipo Vehiculo");

        Txttipovehiculo.setEditable(false);

        jLabel2.setText("Fecha Inicio");

        FechaFin.setText("Fecha Fin");

        lblMonto.setText("Monto");

        txtMonto.setEditable(false);

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgendar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txttipovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIDServicio)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtID_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIDEmpleado)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtID_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnbuscarservicio)
                                    .addComponent(btnbuscarempleado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID_Auto)
                                .addGap(18, 18, 18)
                                .addComponent(txtID_Auto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnbuscarauto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 627, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dtchInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtchFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaFin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDServicio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtID_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscarservicio)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEmpleado)
                    .addComponent(txtID_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarempleado))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID_Auto)
                    .addComponent(txtID_Auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarauto))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txttipovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnAgendar)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FechaFin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtchFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtchInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarservicioActionPerformed
          
        String tipo;
        tipo=Txttipovehiculo.getText();
        if(!txtID_Auto.getText().isEmpty()){
        Frm_Buscar_Servicios buscar = new Frm_Buscar_Servicios(null, true);
        buscar.Cargar(tipo);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String tipo =Txttipovehiculo.getText();
                    String condicion = "";
                    BLServicios logica = new BLServicios();
                    Entidad_Servicio servicio;
                    if (id > -1) {
                          condicion = String.format("Id_Servicio=%d", id);
                        servicio = logica.ObtenerUnServicio(condicion);
                        txtID_Servicio.setText(String.valueOf(servicio.getId()));
                        txtMonto.setText(String.valueOf(servicio.getPrecio()));
                        
                    }
                    else{
                        txtID_Servicio.setText("");
                        
                    } 
                    
                    
                    
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
            
        });
        
        buscar.setVisible(true); 
        
        }
        else{
         JOptionPane.showMessageDialog(null, "Debes primero elegir un automovil");
        
        
        }
        
    
        
    }//GEN-LAST:event_btnbuscarservicioActionPerformed

    private void btnbuscarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarempleadoActionPerformed
            Frm_Buscar_Empleado buscar = new Frm_Buscar_Empleado(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    BLEmpleados logica = new BLEmpleados();
                    EntidadEmpleado empleado;
                    if (id > -1) {
                        condicion = String.format("Id_Empleado=%d", id);
                        empleado = logica.ObtenerUnEmpleado(condicion);
                        txtID_Empleado.setText(String.valueOf(empleado.getId()));
                        
                    }
                    else{
                        txtID_Empleado.setText("");
                        
                    }                      
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        buscar.setVisible(true);    
    }//GEN-LAST:event_btnbuscarempleadoActionPerformed

    private void btnbuscarautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarautoActionPerformed
            Frm_Buscar_Auto buscar = new Frm_Buscar_Auto(null, true);
            buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    BLAuto logica = new BLAuto();
                    EntidadAutomovil auto;
                    if (id > -1) {
                        condicion = String.format("Id_Automovil=%d", id);
                        auto = logica.ObtenerUnAuto(condicion);
                        txtID_Auto.setText(String.valueOf(auto.getId()));
                         Txttipovehiculo.setText(String.valueOf(auto.getTipo_vehiculo()));
                    }
                    else{
                        txtID_Auto.setText("");
                        
                    }                      
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        buscar.setVisible(true); 
        
        
   
        
    }//GEN-LAST:event_btnbuscarautoActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
           BLReparaciones logica = new BLReparaciones();
        EntidadReparaciones reparacion = GenerarEntidad();
        try {
            if (reparacion.isExiste()) {
                //logica.Modificar(reparacion);
            }
            else{
                logica.Insertar(reparacion);
            }
         //   Limpiar();
          //  CargarDatos("");
            JOptionPane.showMessageDialog(this, logica.getMensaje());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR " + ex.getMessage());
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    
    public String getTipoVehiculo(){
    String tipo_vehiculo=Txttipovehiculo.getText();
    
    return tipo_vehiculo;
    };
    
    
     public void setTipoVehiculo( String tipo){
    String tipo_vehiculo=tipo;
    
    
    };
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     private EntidadReparaciones GenerarEntidad(){
        EntidadReparaciones reparacion = new EntidadReparaciones();
        if (!txtID.getText().equals("")) {
            reparacion.setExiste(true);
            reparacion.setId(Integer.parseInt(txtID.getText()));
        }
        reparacion.setId_servicio(Integer.parseInt(txtID_Servicio.getText()));
        reparacion.setId_auto(Integer.parseInt(txtID_Auto.getText()));
        reparacion.setId_empleado(Integer.parseInt(txtID_Empleado.getText()));
       reparacion.setFechaInicio(dtchInicio.getDate());
        reparacion.setFechaFin(dtchFin.getDate());
        reparacion.setMonto( Integer.parseInt(txtMonto.getText()));
        return reparacion;
        
        
        

        
        
        
    }

    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaFin;
    public javax.swing.JTextField Txttipovehiculo;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnbuscarauto;
    private javax.swing.JButton btnbuscarempleado;
    private javax.swing.JButton btnbuscarservicio;
    private com.toedter.calendar.JDateChooser dtchFin;
    private com.toedter.calendar.JDateChooser dtchInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDEmpleado;
    private javax.swing.JLabel lblIDServicio;
    private javax.swing.JLabel lblID_Auto;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID_Auto;
    private javax.swing.JTextField txtID_Empleado;
    private javax.swing.JTextField txtID_Servicio;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
