/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import java.awt.Dimension;

/**
 *
 * @author Fran
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuAuto = new javax.swing.JMenu();
        MnuCliente = new javax.swing.JMenuItem();
        MnuEmpleado = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnuProducto = new javax.swing.JMenuItem();
        MnuReparacion = new javax.swing.JMenuItem();
        MnuPago = new javax.swing.JMenuItem();
        MnuFactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );

        MnuAuto.setText("Menu");
        MnuAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAutoActionPerformed(evt);
            }
        });

        MnuCliente.setText("Clientes");
        MnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuClienteActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuCliente);

        MnuEmpleado.setText("Empleados");
        MnuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEmpleadoActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuEmpleado);

        jMenuItem1.setText("Automoviles");
        MnuAuto.add(jMenuItem1);

        MnuProducto.setText("CompraProducto");
        MnuAuto.add(MnuProducto);

        MnuReparacion.setText("AgendarReparacion");
        MnuAuto.add(MnuReparacion);

        MnuPago.setText("Pagos");
        MnuAuto.add(MnuPago);

        MnuFactura.setText("GenerarFactura");
        MnuAuto.add(MnuFactura);

        jMenuBar1.add(MnuAuto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuAutoActionPerformed

    private void MnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuClienteActionPerformed

        Frm_Clientes Frm_cliente = new Frm_Clientes();
        Escritorio.add(Frm_cliente);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_cliente.getSize();
        Frm_cliente.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_cliente.show();
    }//GEN-LAST:event_MnuClienteActionPerformed

    private void MnuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEmpleadoActionPerformed
        Frm_Empleados Frm_empleados = new Frm_Empleados();
        Escritorio.add(Frm_empleados);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_empleados.getSize();
        Frm_empleados.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_empleados.show();
    }//GEN-LAST:event_MnuEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MnuAuto;
    private javax.swing.JMenuItem MnuCliente;
    private javax.swing.JMenuItem MnuEmpleado;
    private javax.swing.JMenuItem MnuFactura;
    private javax.swing.JMenuItem MnuPago;
    private javax.swing.JMenuItem MnuProducto;
    private javax.swing.JMenuItem MnuReparacion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
