/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Fran
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/mecanico-automoviles-asiatico-taller-reparacion-automoviles-revisando-motor-clientes-que-usan-automoviles-servicios-reparacion-mecanico-trabajara-garaje_140555-248.jpg"));
        Image image = icon.getImage();
        Escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){ g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        ;
        jPanel1 = new javax.swing.JPanel();
        MnuPrincipal = new javax.swing.JMenuBar();
        MnuAuto = new javax.swing.JMenu();
        MnuCliente = new javax.swing.JMenuItem();
        MnuEmpleado = new javax.swing.JMenuItem();
        MnuAutomovil = new javax.swing.JMenuItem();
        MnuProducto = new javax.swing.JMenuItem();
        MnuReparacion = new javax.swing.JMenuItem();
        MnuPago = new javax.swing.JMenuItem();
        mnuPagarMontos = new javax.swing.JMenuItem();
        MnuFactura = new javax.swing.JMenuItem();
        MnuListarFacturas = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        Escritorio.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addGap(964, 964, 964))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1080, Short.MAX_VALUE))
        );

        MnuAuto.setText("Menu");
        MnuAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAutoActionPerformed(evt);
            }
        });

        MnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/team.png"))); // NOI18N
        MnuCliente.setText("Clientes");
        MnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuClienteActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuCliente);

        MnuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/worker.png"))); // NOI18N
        MnuEmpleado.setText("Empleados");
        MnuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEmpleadoActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuEmpleado);

        MnuAutomovil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mechanical.png"))); // NOI18N
        MnuAutomovil.setText("Automoviles");
        MnuAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAutomovilActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuAutomovil);

        MnuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargo.png"))); // NOI18N
        MnuProducto.setText("CompraProducto");
        MnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuProductoActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuProducto);

        MnuReparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mechanic.png"))); // NOI18N
        MnuReparacion.setText("AgendarReparacion");
        MnuReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuReparacionActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuReparacion);

        MnuPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-dinero-de-yandex-32.png"))); // NOI18N
        MnuPago.setText("AsignarPagos");
        MnuPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuPagoActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuPago);

        mnuPagarMontos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-tarjeta-en-uso-32.png"))); // NOI18N
        mnuPagarMontos.setText("Pagar montos pendientes");
        mnuPagarMontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagarMontosActionPerformed(evt);
            }
        });
        MnuAuto.add(mnuPagarMontos);

        MnuFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-invoices-32.png"))); // NOI18N
        MnuFactura.setText("GenerarFactura");
        MnuFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFacturaActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuFactura);

        MnuListarFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-lista-de-verificación-32.png"))); // NOI18N
        MnuListarFacturas.setText("ListarFacturas");
        MnuListarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuListarFacturasActionPerformed(evt);
            }
        });
        MnuAuto.add(MnuListarFacturas);

        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-almacén-32.png"))); // NOI18N
        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        MnuAuto.add(mnuProductos);

        MnuPrincipal.add(MnuAuto);

        setJMenuBar(MnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuAutoActionPerformed

    private void MnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuClienteActionPerformed

        Frm_Clientes Frm_cliente = new Frm_Clientes();
        Escritorio.add(Frm_cliente);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_cliente.getSize();
        Frm_cliente.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_cliente.show();
    }//GEN-LAST:event_MnuClienteActionPerformed

    private void MnuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEmpleadoActionPerformed
        Frm_Empleados Frm_empleados = new Frm_Empleados();
        Escritorio.add(Frm_empleados);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_empleados.getSize();
        Frm_empleados.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_empleados.show();
    }//GEN-LAST:event_MnuEmpleadoActionPerformed

    private void MnuAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAutomovilActionPerformed
        Frm_Agrega_Auto Frm_Autos = new Frm_Agrega_Auto();
        Escritorio.add(Frm_Autos);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Autos.getSize();
        Frm_Autos.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Autos.show(); 
    }//GEN-LAST:event_MnuAutomovilActionPerformed

    private void MnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuProductoActionPerformed
        Frm_Comprar_Producto Frm_Compras = new Frm_Comprar_Producto();
        Escritorio.add(Frm_Compras);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Compras.getSize();
        Frm_Compras.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Compras.show(); 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_MnuProductoActionPerformed

    private void MnuReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuReparacionActionPerformed
        Frm_Agenda_Reparacion Frm_Reparacion = new Frm_Agenda_Reparacion();
        Escritorio.add(Frm_Reparacion);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Reparacion.getSize();
        Frm_Reparacion.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Reparacion.show(); 
        
        
        
        
    }//GEN-LAST:event_MnuReparacionActionPerformed

    private void MnuPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuPagoActionPerformed
        // TODO add your handling code here:
        
        Frm_Transaccion Frm_Transaccion = new Frm_Transaccion();
        Escritorio.add(Frm_Transaccion);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Transaccion.getSize();
        Frm_Transaccion.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
                        ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Transaccion.show(); 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_MnuPagoActionPerformed

    private void mnuPagarMontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagarMontosActionPerformed
       
         Frm_Realizar_Pagos Frm_Pagar_Pendientes = new Frm_Realizar_Pagos();
        Escritorio.add(Frm_Pagar_Pendientes);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Pagar_Pendientes.getSize();
        Frm_Pagar_Pendientes.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
       ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Pagar_Pendientes.show(); 
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_mnuPagarMontosActionPerformed

    private void MnuFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFacturaActionPerformed
        
        Frm_Generar_Factura Frm_Facturas = new Frm_Generar_Factura();
        Escritorio.add(Frm_Facturas);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Facturas.getSize();
        Frm_Facturas.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
       ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Facturas.show(); 
        
        
        
        
        
  
    }//GEN-LAST:event_MnuFacturaActionPerformed

    private void MnuListarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuListarFacturasActionPerformed
         Frm_Listar_Facturas Frm_Facturas = new Frm_Listar_Facturas();
        Escritorio.add(Frm_Facturas);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Facturas.getSize();
        Frm_Facturas.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
       ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Facturas.show(); 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_MnuListarFacturasActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
       Frm_Productos Frm_Productos = new Frm_Productos();
        Escritorio.add(Frm_Productos);
        Dimension sizeContenedor = Escritorio.getSize();
        Dimension sizeFrm = Frm_Productos.getSize();
        Frm_Productos.setLocation((((int) sizeContenedor.getWidth() - (int) sizeFrm.getWidth()) / 2),
       ((int) sizeContenedor.getHeight() - (int) sizeFrm.getHeight()) / 2);
        Frm_Productos.show(); 
        
        
    }//GEN-LAST:event_mnuProductosActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MnuAuto;
    private javax.swing.JMenuItem MnuAutomovil;
    private javax.swing.JMenuItem MnuCliente;
    private javax.swing.JMenuItem MnuEmpleado;
    private javax.swing.JMenuItem MnuFactura;
    private javax.swing.JMenuItem MnuListarFacturas;
    private javax.swing.JMenuItem MnuPago;
    private javax.swing.JMenuBar MnuPrincipal;
    private javax.swing.JMenuItem MnuProducto;
    private javax.swing.JMenuItem MnuReparacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuPagarMontos;
    private javax.swing.JMenuItem mnuProductos;
    // End of variables declaration//GEN-END:variables
}
